language: php
# We want to avoid sudo. This allow us to use Travis docker infrastructure, which means builds start faster and have more CPU available.
sudo: false

php:
  - '5.3'

# We need LDAP as long as it is in express_core. Need CGI for runserver in PHP 5.3.
addons:
  apt:
    packages:
    - ldap-utils
    - curl
    - php5-ldap
    - php5-cgi
    - php5-mysql
    - php5-curl
    - php5-gd

mysql:
  database: drupal
  username: root
  encoding: utf8

# Cache Composer & Drush directories.
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

# Order of operations is: before_install, install, before_script, script,
# after_success or after_failure, OPTIONAL before_deploy, OPTIONAL deploy,
# OPTIONAL after_deploy, after_script.

install:
  # Install latest Drush 6.
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "drush/drush:6.*"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Drupal.org verify tool
  #- drush dl -y drupalorg_drush-7.x-1.x-dev --destination=$HOME/.drush
  #- drush cc drush

  # Build Behat dependencies
  - cd ./tests/behat
  - travis_retry composer install --prefer-dist --no-interaction
  - cd ../../../

  # Build Codebase
  - mkdir profiles
  - mv express profiles/
  - mkdir drupal
  - mv profiles drupal/

  # Build the current branch
  - cd drupal
  - drush make --yes profiles/express/drupal-org-core.make
  #- drush make --yes profiles/express/drupal-org.make --no-core --contrib-destination=profiles/express
  - cd ../

  # Verify that all the .make files will work on Drupal.org.
  #- drush verify-makefile drupal/profiles/express/drupal-org.make
  #- find drupal/profiles/express/modules -name \*.make -print0 | xargs -0 -n1 drush verify-makefile

  # Setup files
  - mkdir -p drupal/sites/default/files/styles/preview/public/gallery/
  - chmod -R 777 drupal/sites
  - mkdir tmp
  - chmod -R 777 tmp

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.1.jar
  - java -jar selenium-server-standalone-2.42.1.jar > /dev/null 2>&1 &
  - nc -zvv localhost 4444; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 4444..."; nc -zvv localhost 4444; out=$?; sleep 5; done

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # Add memcache, APC, and LDAP
  - echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.shm_size=256M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Bump up max execution time.
  - echo "max_execution_time=60" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL connection timeout on the PHP end.
  - echo "mysql.connect_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "default_socket_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL server timetout and packet size.
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 33554432;"

before_script:

  - mysql -e 'create database drupal;'

  # Do the site install (either the current revision or old for the upgrade).
  - cd drupal
  - cp profiles/express/tests/travis-ci/settings.travis.php sites/default/settings.php
  - drush si express --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Express" express_profile_configure_form.cu_express_install_version=0 --yes

  # Enable all the bundles
  - drush en cu_advanced_content_bundle cu_advanced_design_bundle cu_advanced_layout_bundle cu_debug_admin_bundle cu_events_bundle cu_forms_bundle cu_news_bundle cu_people_bundle cu_photo_gallery_bundle cu_seo_bundle cu_social_media_bundle -y

  # Start server.
  - drush runserver 127.0.0.1:8080 &
  - nc -zvv 127.0.0.1 8080; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 8080..."; nc -zvv localhost 8080; out=$?; sleep 5; done
  - cd profiles/express/tests/behat

  # Setting Behat environment
  - BUILD_TOP=`dirname $TRAVIS_BUILD_DIR`
  - BEHAT_PARAMS='{"extensions":{"Drupal\\DrupalExtension":{"drupal":{"drupal_root":"BUILD_TOP/drupal"}},"Behat\\MinkExtension":{"base_url":"http://127.0.0.1:8080/"}}}'
  - BEHAT_PARAMS=`echo $BEHAT_PARAMS | sed -e s#BUILD_TOP#$BUILD_TOP#`
  - export BEHAT_PARAMS

script:
  # Run Behat tests.
  - ./bin/behat --config behat.yml --verbose --tags '~@max_execution_time'
  # Run tests that were timing out.
  - ./bin/behat --config behat.yml --verbose --tags @max_execution_time

notifications:
  slack:
    rooms:
      secure: nO0N58mdD/uOaJy/gN515kRN0WpFTk41eL10/ybSrrHuOLwcZmIGGB5s6JhvYcZnBDmel5AEqqSqQwlOUMUKh6Vv88FtrhFAF0/koq9VRF6MWkBkRvLgEJa3RtERJLNpRae3mKLnC9BpWNrn7Y3seyMpkwhOf7tfO2SygwQJ4DL3nWcrRtcZL0n5WvmXEQ69tulR0ZT1dub1p4gnGu42YqsAeKW4RqpnBEJN8JcYAOIkxlrLcZwqu9HF6/mEHjaBCSVgV+wLdjpSh+16moHnoSXgYfDUSmjDVfCSG46vfz62KoYlHttxDgBUeszDKstrqxPXDBqmmiROY6t/quuSGmpe+xYre2FI7dzA6j0XARxVsf50oeed+1J6eZKztQAKKjiktKEBbjOAP5SWHL1PXw9nXCSUYdXJ3Ry7NjdY6RPc9AljBe7swLBJe4zfg5ptgeoiBdLOzBHVoZXq33dwoV90UKwQq7x72qPPPcIg8aDEha2LmHKM0VgVFb3bow2lydqq0TerDoOI7XE1Qky772B47H/Evp0gvE1oG1m518FqpaKTP52Tz0T+ou7Pf/rG1fGxx6K7D/9+u+gZvmE8emJn33cWAtqBk2JGCduj//cbQWQhgF1QMd4+64qTZxuqPRFWJK0UXIfTgOZRrNeSuVr5/uRmU1ICaQ13ytsAhEU=
